name: Automated Tests
run-name: Automated Tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [lts]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:coverage